model:
  name: sentence-transformers/all-MiniLM-L6-v2
  device: auto
  batch_size: 32

data:
  training_file: data/training.csv
  test_file: data/test.csv
  vector_database_path: data/vector_database
  vector_database_file: vector_database.bin
  metadata_file: metadata.pkl
  
  passage_column: passage
  question_column: question
  answer_column: answer

retrieval:
  top_k: 1
  similarity_threshold: 0.0
  max_passage_length: 1000

evaluation:
  num_samples: 10
  accuracy_threshold: 0.5
  verbose: true

logging:
  level: INFO
  log_dir: logs
  console_output: true
  file_output: true

system:
  max_memory_usage: 4GB
  num_workers: 4
  cache_embeddings: true


